### ISSUE TITLE
Super Dev mode run issue

### ISSUE THREAD

**Issue by nigel-v-thomas** [TDesjardins/gwt-ol3#3]
Thank you for creating this prototype OL3 wrapper!

Calling mvn clean gwt:run-codeserver works okay, however, on trying to run the web server I get the following error:
```
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:166)
	at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:42)
	at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:37)
	at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:114)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:366)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:200)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:82)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxes(CodeServer.java:156)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:118)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:91)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 21 more
```

I tried adding the missing dependency 
```
      <dependency>
          <groupId>asm</groupId>
          <artifactId>asm</artifactId>
          <version>3.3.1</version>
      </dependency>
```
However, with this in place, I get a different error:

```
java.lang.IncompatibleClassChangeError: class com.google.gwt.dev.javac.BytecodeSignatureMaker$CompileDependencyVisitor has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at com.google.gwt.dev.javac.BytecodeSignatureMaker.visitCompileDependenciesInBytecode(BytecodeSignatureMaker.java:227)
	at com.google.gwt.dev.javac.BytecodeSignatureMaker.getCompileDependencySignature(BytecodeSignatureMaker.java:209)
	at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:166)
	at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:42)
	at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:37)
	at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:114)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:366)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:200)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:82)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxes(CodeServer.java:156)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:118)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:91)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by nigel-v-thomas** [comment]
Thanks @TDesjardins , I had resolved this issue by adding asm 5.x to my dependency tree not sure why i need this..

>         <dependency>
>             <groupId>org.ow2.asm</groupId>
>             <artifactId>asm</artifactId>
>             <version>5.0.4</version>
>             <scope>provided</scope>
>         </dependency>

**Comment by TDesjardins** [comment]
Hi @nigel-v-thomas,

probably you only need the asm dependencies of the gwt-dev.jar.

**Comment by nigel-v-thomas** [comment]
Perfect, thanks @TDesjardins. Now replaced with gwt-dev - does the trick.
